use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

/// Response from the OpenAI Responses API
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Response {
    /// Unique identifier for the response
    pub id: String,
    
    /// The model used to generate the response
    pub model: String,
    
    /// The output items generated by the model
    pub output_items: Vec<crate::types::ResponseItem>,
    
    /// Optional ID of the previous response in the conversation
    pub previous_response_id: Option<String>,
    
    /// Creation timestamp
    #[serde(with = "chrono::serde::ts_seconds")]
    pub created_at: DateTime<Utc>,
    
    /// Optional metadata associated with the response
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl Response {
    /// Gets the ID of this response
    pub fn id(&self) -> &str {
        &self.id
    }
    
    /// Gets the text content of the response, concatenating all text items
    pub fn output_text(&self) -> String {
        self.output_items
            .iter()
            .filter_map(|item| match item {
                crate::types::ResponseItem::Text { content, .. } => Some(content.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("")
    }
    
    /// Gets all tool calls from the response
    pub fn tool_calls(&self) -> Vec<&crate::types::ToolCall> {
        self.output_items
            .iter()
            .filter_map(|item| match item {
                crate::types::ResponseItem::ToolCall(tool_call) => Some(tool_call),
                _ => None,
            })
            .collect()
    }
}
